### ISSUE TITLE
Last online bug

### ISSUE THREAD

**Issue by wilsonhyng** [M1nistry/GuildStatus#2]
http://imgur.com/Prkoqa7

I don't think the game was around in 1969 :)

**Comment by M1nistry** [comment]
The way the datetime is returned from the JSON request uses Unix time (http://en.wikipedia.org/wiki/Unix_time) which works by giving the total amount of seconds since 31/12/1969, so essentially if it returns a 1969 year it's basically returning no value. I'll fix this so the cell is empty in this situation though as it can be misleading. Thanks!
